#  Cálculo del ranking  de paises sudamericanos que participaron en las eliminatorias para el mundial Rusia 2018  usando el algoritmo PageRank.

## Algoritmo PageRank:
<div class=text-justify>
### PageRank es una marca registrada y patentada1  por Google el 9 de enero de 1999 que ampara una familia de algoritmos utilizados para asignar de forma numérica la relevancia de los documentos (o páginas web) indexados por un motor de búsqueda. El primer documento sobre el proyecto, que describe el PageRank y el prototipo inicial del motor de búsqueda de Google, se publicó en 1998. Sus propiedades son muy discutidas por los expertos en optimización de motores de búsqueda. El sistema PageRank es utilizado por el popular motor de búsqueda Google para ayudarle a determinar la importancia o relevancia de una página. Fue desarrollado por los fundadores de Google, Larry Page (apellido, del cual, recibe el nombre este algoritmo) y Sergey Brin, en la Universidad de Stanford mientras estudiaban el posgrado en ciencias de la computación.

### PageRank confía en la naturaleza democrática de la web utilizando su vasta estructura de enlaces como un indicador del valor de una página en concreto. Google interpreta un enlace de una página A a una página B como un voto, de la página A, para la página B. Pero Google mira más allá del volumen de votos, o enlaces que una página recibe; también analiza la página que emite el voto. Los votos emitidos por las páginas consideradas "importantes", es decir con un PageRank elevado, valen más, y ayudan a hacer a otras páginas "importantes". Por lo tanto, el PageRank de una página refleja la importancia de la misma en Internet. 

## 2. Importancia en la web y motores de búsqueda
### Anteriormente el Pagerank era la base del motor de búsqueda Google, un sistema de clasificación que cuando los motores de búsqueda fueron desarrollados por primera vez, la clasificación que se hacia para todos los sitios web era la misma, por lo que los resultados obtenidos estaban basados únicamente en las etiquetas de contenido. 
### n ese entonces el Pagerank revoluciono el posicionamiento de las paginas web en los buscadores a través de la incorporación de una pieza fundamental, la autoridad o relevancia de un sitio web. Para poder determinar esta importancia o autoridad, Google escogió varias páginas web de mayor envergadura a las que vinculaba otro sitio web el cual recibía una porción de esa autoridad o importancia.
### Con el uso de esta técnica de transmitir relevancia, Google pudo contar la autoridad de una pagina web y establecer una table del 0 al 10 a la que se le conoció como Pagerank. La importancia de este componente en el entramado del posicionamiento de una pagina web es básico para todo webmaster que recién comienza y mucho más para los que ya tienen más experiencia. Hay que mencionar que el Pagerank de una pagina web puede conocerse fácilmente a través de Internet ya que existen muchos portales que ofrecen este servicio, sin embargo es importante mencionar que este valor es solamente una estimación que Google establece y que suele actualizarse cada 3 meses aproximadamente.
### Asimismo, el Pagerank de una pagina web es de mucho interés no solamente para los motores de búsqueda, sino también para los compradores de enlaces, los propios dueños de paginas web, personas que trabajan en marketing y en general todos aquellos que estén interesados en el valor que se le da aun sitio web con la intención de conocer que tan importante es o cuanta relevancia tiene con respecto a otros sitios con contenido similar. Debido a que muchos webmasters han logrado incrementar el Pagerank artificialmente, Google ha endurecido las medidas que determinar la importancia de un sitio web por lo que en la actualidad disminuido, pero que sigue siendo básico para las paginas en Internet.
### En lugar de actualizar los cada semana, Google ha optado por hacerlo cada cuatro años, por lo que ahora es más complicado conocer el verdadero valor de una pagina web. La única forma de conseguir Pagerank es conseguir un enlace a una sitio web que ya cuenta con una valor de Pagerank, sin embargo conseguir una gran cantidad de enlaces de una pagina web con Pagerank 0, no ayudara en nada incrementar el Pagerank de la pagina, pero por el contrario si se enlaza con una pagina con Pagerank 6, casi al instante se puede incrementar el valor de Pagerank de un sito a 5, en caso de que sea de la confianza de Google y no existan más vínculos con otras paginas web.



## 2. Algoritmo:

### Algoritmo PageRank  
<div class=text-justify>
### Usaremos un caso particular 
### Definimos nuestra matriz de adyacencia con los equipos sudamericanos que participaron para las eliminatorias del Mundial Rusia 2018
#### Orden para cada País que participo en las eliminatorias

1.  Argentina	
2.  Bolivia	
3.  Brasil	
4.  Chile	
5.  Colombia	
6.  Ecuador	
7.  Paraguay	
8.  Perú	
9.  Uruguay	
10. Venezuela

#### Definimos nuestra matriz de adyacencia
#### A[i,j] = 3 si el país 'i' le gano al país 'j'
#### A[i,j] = 1 si el país 'i' empato con país 'j'
#### A[i,j] = 0 si el país 'i' perdió con el país 'j'


In [6]:
num_equipos <- 10
#Se implementa la matriz
A <- matrix(c(0, 3, 1 ,3, 3 ,0, 0, 1, 3, 1, 
              3, 0, 1, 3, 0, 1, 3, 0, 0, 3,
              3, 3, 0, 3, 3, 3, 3, 3, 1, 3, 
              0, 0, 0, 0, 1, 3, 0, 3, 3, 3, 
              0, 3, 1, 1, 0, 3, 0, 3, 1, 3, 
              0, 3, 0, 3, 0, 0, 1, 0, 3, 3,
              1, 3, 1, 3, 0, 3, 0, 0, 0, 0,
              1, 3, 0, 0, 1, 3, 3, 0, 3, 1, 
              1, 3, 0, 3, 3, 3, 3, 3, 0, 3, 
              1, 3, 0, 0, 1, 0, 0, 1, 1, 0),
            nrow = num_equipos,ncol = num_equipos,byrow = TRUE)
A
#graficamos en grafo 
library( igraph )
plot(graph.adjacency(A))


[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,] 0    3    1    3    3    0    0    1    3    1    
 [2,] 3    0    1    3    0    1    3    0    0    3    
 [3,] 3    3    0    3    3    3    3    3    1    3    
 [4,] 0    0    0    0    1    3    0    3    3    3    
 [5,] 0    3    1    1    0    3    0    3    1    3    
 [6,] 0    3    0    3    0    0    1    0    3    3    
 [7,] 1    3    1    3    0    3    0    0    0    0    
 [8,] 1    3    0    0    1    3    3    0    3    1    
 [9,] 1    3    0    3    3    3    3    3    0    3    
[10,] 1    3    0    0    1    0    0    1    1    0

ERROR: Error in library(igraph): there is no package called ‘igraph’


#### Primero tenemos que crear una nueva matrix A1 que resultará de dividir cada columna de la matriz A entre la suma de cada columna

In [7]:
A1 <- matrix(nrow = num_equipos,ncol= num_equipos)
#calculamos la matriz de probabilidades dónde la suma debe ser de cada columna debe ser 1
for( i in 1:num_equipos){
  sum_columna <- sum(A[,i])
  A1[,i] = A[,i]/sum_columna
}
A1


[,1] [,2]  [,3] [,4]       [,5]       [,6]       [,7]       [,8]      
 [1,] 0.0  0.125 0.25 0.15789474 0.25000000 0.00000000 0.00000000 0.07142857
 [2,] 0.3  0.000 0.25 0.15789474 0.00000000 0.05263158 0.23076923 0.00000000
 [3,] 0.3  0.125 0.00 0.15789474 0.25000000 0.15789474 0.23076923 0.21428571
 [4,] 0.0  0.000 0.00 0.00000000 0.08333333 0.15789474 0.00000000 0.21428571
 [5,] 0.0  0.125 0.25 0.05263158 0.00000000 0.15789474 0.00000000 0.21428571
 [6,] 0.0  0.125 0.00 0.15789474 0.00000000 0.00000000 0.07692308 0.00000000
 [7,] 0.1  0.125 0.25 0.15789474 0.00000000 0.15789474 0.00000000 0.00000000
 [8,] 0.1  0.125 0.00 0.00000000 0.08333333 0.15789474 0.23076923 0.00000000
 [9,] 0.1  0.125 0.00 0.15789474 0.25000000 0.15789474 0.23076923 0.21428571
[10,] 0.1  0.125 0.00 0.00000000 0.08333333 0.00000000 0.00000000 0.07142857
      [,9]       [,10]
 [1,] 0.20000000 0.05 
 [2,] 0.00000000 0.15 
 [3,] 0.06666667 0.15 
 [4,] 0.20000000 0.15 
 [5,] 0.06666667 0.15 
 [6,] 0.20000000 0.15 
 [7,] 0.00000000 0.00 
 [8,] 0.20000000 0.05 
 [9,] 0.00000000 0.15 
[10,] 0.06666667 0.00

##### El siguiente paso es encontra un vector pagerank_equipos de tamaño 10 que represente el PageRank de cada equipo, y ¿cómo es ese vector? Pues es el vector propio del máximo valor propio
#### Aprovechando el uso de R, utilizaremos la función eigen() para obtener los valores y vectores propios

In [5]:
vector_ValoresPropios <- c(eigen(A1)$values)
vector_VectoresPropios <- matrix(eigen(A1)$vectors,nrow = 10, ncol = 10)
print(Mod(vector_ValoresPropios))
print(Mod(vector_VectoresPropios))

 [1] 1.00000000 0.39837662 0.25441107 0.25441107 0.24536339 0.24536339
 [7] 0.21468098 0.05836344 0.05539562 0.02231747
           [,1]       [,2]       [,3]       [,4]       [,5]       [,6]
 [1,] 0.3793522 0.32945265 0.34835701 0.34835701 0.44262544 0.44262544
 [2,] 0.3616417 0.03076198 0.52287818 0.52287818 0.23755452 0.23755452
 [3,] 0.4738853 0.59078300 0.06964756 0.06964756 0.04749232 0.04749232
 [4,] 0.2163052 0.14918475 0.47003095 0.47003095 0.27669290 0.27669290
 [5,] 0.3153363 0.42852429 0.26574383 0.26574383 0.49037723 0.49037723
 [6,] 0.1977172 0.20065120 0.06504935 0.06504935 0.14474449 0.14474449
 [7,] 0.2669837 0.15904165 0.37215412 0.37215412 0.20900447 0.20900447
 [8,] 0.2846076 0.06974278 0.33309057 0.33309057 0.43495536 0.43495536
 [9,] 0.3731390 0.51087886 0.21435288 0.21435288 0.40988057 0.40988057
[10,] 0.1546235 0.06468793 0.09601846 0.09601846 0.08089607 0.08089607
            [,7]        [,8]       [,9]      [,10]
 [1,] 0.11917992 0.006020933 0.15529263 0.095980

#### Ahora calculamos cual es el máximo valor propio.

In [8]:
maxVP <- -Inf
for(i in 1:10){
  if(maxVP < Mod(vector_ValoresPropios[i])){
    maxVP <- Mod(vector_ValoresPropios[i])
    #indice relacionado con el máximo valor propio
    index <- i
  } 
}

ERROR: Error in eval(expr, envir, enclos): object 'vector_ValoresPropios' not found


#### Imprimimos el máximo valor propio

In [8]:
print(maxVP)

[1] 1


#### Imprimimos el vector propio relacionado a ese vector

In [9]:
pagerank_equipos <- Mod(vector_VectoresPropios[,index])
print("Argentina Bolivia Brasil Chile Colombia Ecuador Paraguay Perú Uruguay Venezuela")
print(pagerank_equipos)

[1] "Argentina Bolivia Brasil Chile Colombia Ecuador Paraguay Perú Uruguay Venezuela"
 [1] 0.3793522 0.3616417 0.4738853 0.2163052 0.3153363 0.1977172 0.2669837
 [8] 0.2846076 0.3731390 0.1546235


### Ahora ya tenemos el pagerank de cada uno